[book]
title = "Reproducible HPC-as-a-Service with NixOS Compose"
authors = ["unk1ndled"]
description = "Architecture and tutorials for the Exa-AToW NixOS Compose demonstrator"
language = "en"
multilingual = false
src = "docs"

[build]
build-dir = "book"
create-missing = false

[output.html]
additional-css = ["docs/theme/custom.css"]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://gricad-gitlab.univ-grenoble-alpes.fr/exa-atow/canonical-exa-atow-with-nxc"
git-repository-icon = "fa-gitlab"
edit-url-template = "https://gricad-gitlab.univ-grenoble-alpes.fr/exa-atow/canonical-exa-atow-with-nxc/-/edit/main/{path}"

[output.html.fold]
enable = true
level = 1
