[default]
log_level = 0
data_dir = ./data
default_life_span = 300
max_life_span = 3600
tag_min_size = 3
tag_max_size = 256

grace_time = 2
error_grace_time = 10
housekeeping_interval = 5
search_limit = 20
search_max_limit = 300

#storage_backend = file://
storage_backend = memory://
default_size = 65530

# 2500 * 1024*1024
max_size = 2621440000

auth_backend = auth::passfile
default_user = anonymous
default_email = anonymous@anonymous.org


[db]
 # sqlite:// for in-memory
URL = sqlite:///%(data_dir)s/eb_database.db
clean_startup = true
#URL = sqlite://


[auth::passfile]
# To be put in config file .eb-secret.ini
user_list = [ [ "admin", "admin", { "email": "admin@aqmo.org" }] ]

[backend::memory]
max_total_size = 2000000000

[backend::file]
# 4 * 1024 * 1024
chunk_size = 4194304
session_apoptosis_s = 120
storage_namespace = /ebuffers.aqmo.org/
storage_dir = %(data_dir)s/ephemeral_buffer_files
