[default]
log_level = 0
data_dir = ./data
tag_min_size = 3
tag_max_size = 256

housekeeping_interval = 5
search_limit = 20
search_max_limit = 300

#storage_backend = file://
storage_backend = memory://
default_size = 65530

auth_backend = auth::passfile
default_user = anonymous
default_email = anonymous@anonymous.org


[db]
 # sqlite:// for in-memory
URL = sqlite:///%(data_dir)s/eb_database.db
clean_startup = true
#URL = sqlite://




[auth::passfile]
# To be put in config file .eb-secret.ini
# Example : user_list = [ [ "admin", "password", { "email": "admin@aqmo.org" }] ]
user_list = [ [ "admin", "admin", { "email": "admin@aqmo.org" }] ]
